### ISSUE TITLE
Object#to_latex is not a good idea (name clash with Kramdown)

### ISSUE THREAD

**Issue by dmke** [cie/to_latex#1]
Defining [`Object.to_latex`](/cie/to_latex/blob/master/lib/to_latex.rb#L80-L82) causes the [Kramdown](http://kramdown.rubyforge.net) gem to stop working, since `Kramdown::Document#to_latex` relies on `method_missing` to [find](/gettalong/kramdown/blob/master/lib/kramdown/document.rb#L113-L126) the `Latex` converter:

```
$ irb -rkramdown -rto_latex
irb> Kramdown::Document.new('markdown **bold** test').to_latex
=> "\\#<Kramdown::Document:0x007f30e76302d0>"

$ irb -rkramdown
irb> Kramdown::Document.new('markdown **bold** test').to_latex
=> "markdown \\textbf{bold} test\n\n"
```

**Comment by cie** [comment]
Hi,

It's great you use to_latex. Personally I gave up the original project I
created to_latex for, so I'd be interested in how you would like to use it.
Can you explain how you use it or can you show your repo? Maybe it helps me
come up with a solution.

2013/8/2 Dominik Menke notifications@github.com

**Comment by dmke** [comment]
Just as mentioned above, I have a Rails application using both to_latex and Kramdown. This app takes user input to build some complex PDF through (Xe)LaTeX, and to_latex was an easy way to sanitize short input sequences such as usernames, address bits etc.

Kramdown was just added recently to enable some larger text processing—the (in many cases non-academic) user should not be confronted with LaTeX, both for reasons of security and sanity (complexity). Since Kramdown [also has an escaping mechanism](/gettalong/kramdown/blob/master/lib/kramdown/converter/latex.rb#L583-L596) (and, as described above, doesn't work well with to_latex), I then tossed the to_latex gem a little away.

I'd really like to see the removal of `Object#to_latex` (or at least moving this part in a seperate file, which could be `require`'d if neccessary), so I can express `<%= @user.email.to_latex %>` in my templates. (I currently have a `latex_escape(str)` method, which isn't as catchy—I could make that an instance method of the String class, though ;-))

**Comment by cie** [comment]
Well, a global to_latex method really does not make much sense. I think it can be removed. What do you think about this solution:
- Move Object#to_latex and Object#to_latex_math to a new module called ToLatex::Convertible
- Include ToLatex::Convertible into Integer (so that currently existing specs pass)
- release 0.5.0

**Comment by dmke** [comment]
I'm fine with that :+1:

**Comment by cie** [comment]
Done :)
